In [1]:
#Importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

In [2]:
#Loading the dataset
patients_data = pd.read_csv("plan b data.csv", index_col=0)

In [3]:
#Displaying patients features' table
patients_data

,Diagnosis,VisualG,SUVmax,TBR,ConclusionPET,ABusepostoper,minimum_intensity,maximum_intensity,range,mean_intensity,...,gray_level_nonuniformity_A,size_zone_nonuniformity,zone_percentage,low_gray_level_zone_emphasis,high_gray_level_zone_emphasis,small_zone_low_gray_level_emphasis,small_zone_high_gray_level_emphasis,large_zone_low_gray_level_emphasis,large_zone_high_gray_level_emphasis,filter_$
Patients,,,,,,,,,,,,,,,,,,,,,
1,1,4,6.7,3.72,2,1,0.62,6.68,6.07,2.34,...,16.08,25.22,0.00,0.23,9.939963e+07,0.01,9.860538e+07,11.75,1.229531e+08,0
2,1,3,9.8,4.90,1,1,0.34,9.66,9.32,2.61,...,68.59,37.58,0.00,0.40,2.941573e+08,0.01,2.939368e+08,28.57,3.034294e+08,0
3,1,3,5.3,4.42,1,1,0.08,5.28,5.20,1.72,...,20.20,18.46,0.00,0.36,1.688961e+09,0.03,1.688835e+09,10.02,1.691300e+09,0
4,1,4,11.2,10.18,1,1,0.47,8.50,8.03,2.21,...,11.73,8.39,0.00,0.29,1.263940e+07,0.01,1.259057e+07,31.82,1.366822e+07,0
5,1,4,9.1,6.59,1,1,0.60,8.30,7.70,2.71,...,10.32,5.95,0.00,0.36,1.278671e+07,0.01,1.277919e+07,31.71,1.305688e+07,0
6,1,4,6.3,3.94,1,1,0.70,6.28,5.58,2.70,...,6.46,7.92,0.00,0.33,3.082371e+06,0.01,3.017416e+06,23.82,5.376431e+06,0
7,1,4,4.9,4.45,1,1,0.48,4.87,4.39,1.70,...,7.19,11.14,0.00,0.25,7.772283e+07,0.02,7.742148e+07,9.02,8.304376e+07,0
8,1,4,6.1,4.69,1,1,0.82,6.11,5.29,2.36,...,2.59,3.77,0.00,0.21,1.662223e+06,0.01,1.625534e+06,12.66,2.738375e+06,0
9,1,3,10.3,2.86,1,1,0.44,6.76,6.32,3.01,...,43.75,30.46,0.02,0.35,1.049818e+04,0.03,3.211200e+02,15.54,4.590263e+05,0
10,1,2,7.5,2.88,3,1,0.68,7.49,6.81,3.02,...,7.67,7.62,0.02,0.28,3.609890e+03,0.01,3.368000e+02,22.22,1.051140e+05,0
11,0,0,4.9,2.89,2,1,0.28,4.91,4.63,1.76,...,13.41,15.37,0.00,0.32,9.204362e+08,0.03,9.202316e+08,7.57,9.241926e+08,1
12,0,4,6.9,3.83,3,1,0.38,6.93,6.56,2.49,...,29.67,28.04,0.00,0.34,1.247711e+08,0.02,1.247132e+08,12.28,1.270904e+08,1
13,0,4,9.3,7.75,3,1,0.20,9.29,9.09,1.82,...,24.60,14.46,0.00,0.35,1.342649e+07,0.01,1.332718e+07,33.30,1.521203e+07,1
14,0,3,3.5,1.94,3,1,0.67,3.46,2.78,2.14,...,2.21,4.29,0.00,0.22,1.603004e+06,0.02,1.595393e+06,4.07,1.812258e+06,1
15,0,3,4.3,2.15,2,1,0.39,4.28,3.89,1.90,...,5.00,6.14,0.00,0.31,8.623205e+07,0.03,8.618371e+07,8.79,8.747664e+07,1
16,0,3,6.1,4.36,3,1,0.21,6.08,5.87,2.49,...,15.82,22.87,0.00,0.25,2.545060e+08,0.02,2.544970e+08,10.52,2.548466e+08,1
17,0,2,4.8,2.18,3,2,0.37,4.80,4.43,1.79,...,3.22,6.03,0.00,0.25,3.242638e+06,0.03,3.211116e+06,7.07,3.975808e+06,0
18,0,1,3.0,2.14,2,1,0.55,2.94,2.40,1.47,...,11.95,18.20,0.00,0.39,6.186955e+07,0.03,6.062504e+07,9.68,8.133587e+07,0
19,0,0,9.3,7.75,2,2,0.44,9.29,8.85,1.73,...,13.21,7.08,0.00,0.36,5.708569e+06,0.02,5.682747e+06,35.20,6.127380e+06,0
20,0,2,4.3,3.07,2,2,0.32,4.32,4.00,1.92,...,11.70,13.50,0.00,0.31,2.481976e+07,0.02,2.425409e+07,10.32,3.749502e+07,0
21,0,1,3.0,1.67,2,2,0.37,3.02,2.64,1.60,...,3.13,7.07,0.00,0.29,1.517345e+07,0.04,1.496157e+07,3.52,1.937328e+07,0
22,0,1,2.6,1.63,2,2,0.34,2.60,2.26,1.48,...,2.95,10.45,0.00,0.12,1.439837e+07,0.01,1.404829e+07,1.84,2.027571e+07,0
23,0,1,2.4,3.43,2,2,0.15,2.67,2.52,1.22,...,1.81,7.59,0.00,0.13,3.365668e+06,0.02,3.115217e+06,1.87,6.583081e+06,0
24,0,1,3.4,1.70,2,2,0.36,3.44,3.09,1.84,...,6.79,13.57,0.00,0.34,1.580597e+07,0.05,1.548672e+07,6.42,2.260249e+07,0
25,0,3,5.9,3.47,2,2,0.92,5.08,4.16,2.72,...,8.30,10.65,0.00,0.38,8.774879e+06,0.02,8.732541e+06,12.79,1.052670e+07,0
26,0,0,5.6,3.29,3,2,0.25,5.60,5.35,2.12,...,9.14,12.18,0.00,0.35,8.892132e+06,0.05,8.492991e+06,7.04,1.979140e+07,0
27,0,2,4.7,3.13,2,2,0.32,4.54,4.22,1.80,...,9.03,10.52,0.00,0.33,2.079918e+07,0.04,2.063673e+07,7.89,2.414572e+07,0
28,0,2,3.2,2.91,2,2,0.78,3.01,2.23,1.66,...,4.00,6.71,0.00,0.36,6.473374e+06,0.03,6.462423e+06,6.26,6.675458e+06,0
29,0,3,3.7,2.85,2,2,0.39,3.69,3.30,1.75,...,6.16,9.96,0.00,0.33,8.157497e+06,0.04,7.859610e+06,5.64,1.403711e+07,0
30,0,1,2.5,1.92,2,2,0.22,2.52,2.30,0.94,...,7.59,17.08,0.00,0.30,2.553528e+08,0.03,2.522005e+08,5.30,2.806385e+08,0

In [4]:
#In practice, feature selection should be done after data pre-processing, so ideally, all the categorical variables are encoded into numbers
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(patients_data.select_dtypes(include=numerics).columns)
patients_data = patients_data[numerical_vars]
patients_data

,Diagnosis,VisualG,SUVmax,TBR,ConclusionPET,ABusepostoper,minimum_intensity,maximum_intensity,range,mean_intensity,...,gray_level_nonuniformity_A,size_zone_nonuniformity,zone_percentage,low_gray_level_zone_emphasis,high_gray_level_zone_emphasis,small_zone_low_gray_level_emphasis,small_zone_high_gray_level_emphasis,large_zone_low_gray_level_emphasis,large_zone_high_gray_level_emphasis,filter_$
Patients,,,,,,,,,,,,,,,,,,,,,
1,1,4,6.7,3.72,2,1,0.62,6.68,6.07,2.34,...,16.08,25.22,0.00,0.23,9.939963e+07,0.01,9.860538e+07,11.75,1.229531e+08,0
2,1,3,9.8,4.90,1,1,0.34,9.66,9.32,2.61,...,68.59,37.58,0.00,0.40,2.941573e+08,0.01,2.939368e+08,28.57,3.034294e+08,0
3,1,3,5.3,4.42,1,1,0.08,5.28,5.20,1.72,...,20.20,18.46,0.00,0.36,1.688961e+09,0.03,1.688835e+09,10.02,1.691300e+09,0
4,1,4,11.2,10.18,1,1,0.47,8.50,8.03,2.21,...,11.73,8.39,0.00,0.29,1.263940e+07,0.01,1.259057e+07,31.82,1.366822e+07,0
5,1,4,9.1,6.59,1,1,0.60,8.30,7.70,2.71,...,10.32,5.95,0.00,0.36,1.278671e+07,0.01,1.277919e+07,31.71,1.305688e+07,0
6,1,4,6.3,3.94,1,1,0.70,6.28,5.58,2.70,...,6.46,7.92,0.00,0.33,3.082371e+06,0.01,3.017416e+06,23.82,5.376431e+06,0
7,1,4,4.9,4.45,1,1,0.48,4.87,4.39,1.70,...,7.19,11.14,0.00,0.25,7.772283e+07,0.02,7.742148e+07,9.02,8.304376e+07,0
8,1,4,6.1,4.69,1,1,0.82,6.11,5.29,2.36,...,2.59,3.77,0.00,0.21,1.662223e+06,0.01,1.625534e+06,12.66,2.738375e+06,0
9,1,3,10.3,2.86,1,1,0.44,6.76,6.32,3.01,...,43.75,30.46,0.02,0.35,1.049818e+04,0.03,3.211200e+02,15.54,4.590263e+05,0
10,1,2,7.5,2.88,3,1,0.68,7.49,6.81,3.02,...,7.67,7.62,0.02,0.28,3.609890e+03,0.01,3.368000e+02,22.22,1.051140e+05,0
11,0,0,4.9,2.89,2,1,0.28,4.91,4.63,1.76,...,13.41,15.37,0.00,0.32,9.204362e+08,0.03,9.202316e+08,7.57,9.241926e+08,1
12,0,4,6.9,3.83,3,1,0.38,6.93,6.56,2.49,...,29.67,28.04,0.00,0.34,1.247711e+08,0.02,1.247132e+08,12.28,1.270904e+08,1
13,0,4,9.3,7.75,3,1,0.20,9.29,9.09,1.82,...,24.60,14.46,0.00,0.35,1.342649e+07,0.01,1.332718e+07,33.30,1.521203e+07,1
14,0,3,3.5,1.94,3,1,0.67,3.46,2.78,2.14,...,2.21,4.29,0.00,0.22,1.603004e+06,0.02,1.595393e+06,4.07,1.812258e+06,1
15,0,3,4.3,2.15,2,1,0.39,4.28,3.89,1.90,...,5.00,6.14,0.00,0.31,8.623205e+07,0.03,8.618371e+07,8.79,8.747664e+07,1
16,0,3,6.1,4.36,3,1,0.21,6.08,5.87,2.49,...,15.82,22.87,0.00,0.25,2.545060e+08,0.02,2.544970e+08,10.52,2.548466e+08,1
17,0,2,4.8,2.18,3,2,0.37,4.80,4.43,1.79,...,3.22,6.03,0.00,0.25,3.242638e+06,0.03,3.211116e+06,7.07,3.975808e+06,0
18,0,1,3.0,2.14,2,1,0.55,2.94,2.40,1.47,...,11.95,18.20,0.00,0.39,6.186955e+07,0.03,6.062504e+07,9.68,8.133587e+07,0
19,0,0,9.3,7.75,2,2,0.44,9.29,8.85,1.73,...,13.21,7.08,0.00,0.36,5.708569e+06,0.02,5.682747e+06,35.20,6.127380e+06,0
20,0,2,4.3,3.07,2,2,0.32,4.32,4.00,1.92,...,11.70,13.50,0.00,0.31,2.481976e+07,0.02,2.425409e+07,10.32,3.749502e+07,0
21,0,1,3.0,1.67,2,2,0.37,3.02,2.64,1.60,...,3.13,7.07,0.00,0.29,1.517345e+07,0.04,1.496157e+07,3.52,1.937328e+07,0
22,0,1,2.6,1.63,2,2,0.34,2.60,2.26,1.48,...,2.95,10.45,0.00,0.12,1.439837e+07,0.01,1.404829e+07,1.84,2.027571e+07,0
23,0,1,2.4,3.43,2,2,0.15,2.67,2.52,1.22,...,1.81,7.59,0.00,0.13,3.365668e+06,0.02,3.115217e+06,1.87,6.583081e+06,0
24,0,1,3.4,1.70,2,2,0.36,3.44,3.09,1.84,...,6.79,13.57,0.00,0.34,1.580597e+07,0.05,1.548672e+07,6.42,2.260249e+07,0
25,0,3,5.9,3.47,2,2,0.92,5.08,4.16,2.72,...,8.30,10.65,0.00,0.38,8.774879e+06,0.02,8.732541e+06,12.79,1.052670e+07,0
26,0,0,5.6,3.29,3,2,0.25,5.60,5.35,2.12,...,9.14,12.18,0.00,0.35,8.892132e+06,0.05,8.492991e+06,7.04,1.979140e+07,0
27,0,2,4.7,3.13,2,2,0.32,4.54,4.22,1.80,...,9.03,10.52,0.00,0.33,2.079918e+07,0.04,2.063673e+07,7.89,2.414572e+07,0
28,0,2,3.2,2.91,2,2,0.78,3.01,2.23,1.66,...,4.00,6.71,0.00,0.36,6.473374e+06,0.03,6.462423e+06,6.26,6.675458e+06,0
29,0,3,3.7,2.85,2,2,0.39,3.69,3.30,1.75,...,6.16,9.96,0.00,0.33,8.157497e+06,0.04,7.859610e+06,5.64,1.403711e+07,0
30,0,1,2.5,1.92,2,2,0.22,2.52,2.30,0.94,...,7.59,17.08,0.00,0.30,2.553528e+08,0.03,2.522005e+08,5.30,2.806385e+08,0

In [5]:
#Separating the data into training and tests set
X_train, X_test, y_train, y_test = train_test_split(patients_data.drop(labels=['Diagnosis'], axis=1),
    patients_data['Diagnosis'],
    test_size=0.3,
    random_state=0)
X_train, X_test

(          VisualG  SUVmax    TBR  ConclusionPET  ABusepostoper  \
 Patients
 23              1     2.4   3.43              2              2
 6               4     6.3   3.94              1              1
 17              2     4.8   2.18              3              2
 9               3    10.3   2.86              1              1
 15              3     4.3   2.15              2              1
 24              1     3.4   1.70              2              2
 21              1     3.0   1.67              2              2
 2               3     9.8   4.90              1              1
 30              1     2.5   1.92              2              2
 7               4     4.9   4.45              1              1
 5               4     9.1   6.59              1              1
 19              0     9.3   7.75              2              2
 20              2     4.3   3.07              2              2
 10              2     7.5   2.88              3              1
 8               4     6.1   4.69              1              1
 26              0     5.6   3.29              3              2
 4               4    11.2  10.18              1              1
 1               4     6.7   3.72              2              1
 22              1     2.6   1.63              2              2
 16              3     6.1   4.36              3              1
 13              4     9.3   7.75              3              1

           minimum_intensity  maximum_intensity  range  mean_intensity  \
 Patients
 23                     0.15               2.67   2.52            1.22
 6                      0.70               6.28   5.58            2.70
 17                     0.37               4.80   4.43            1.79
 9                      0.44               6.76   6.32            3.01
 15                     0.39               4.28   3.89            1.90
 24                     0.36               3.44   3.09            1.84
 21                     0.37               3.02   2.64            1.60
 2                      0.34               9.66   9.32            2.61
 30                     0.22               2.52   2.30            0.94
 7                      0.48               4.87   4.39            1.70
 5                      0.60               8.30   7.70            2.71
 19                     0.44               9.29   8.85            1.73
 20                     0.32               4.32   4.00            1.92
 10                     0.68               7.49   6.81            3.02
 8                      0.82               6.11   5.29            2.36
 26                     0.25               5.60   5.35            2.12
 4                      0.47               8.50   8.03            2.21
 1                      0.62               6.68   6.07            2.34
 22                     0.34               2.60   2.26            1.48
 16                     0.21               6.08   5.87            2.49
 13                     0.20               9.29   9.09            1.82

           quantile0025  ...  gray_level_nonuniformity_A  \
 Patients                ...
 23                0.33  ...                        1.81
 6                 1.17  ...                        6.46
 17                0.59  ...                        3.22
 9                 0.98  ...                       43.75
 15                0.71  ...                        5.00
 24                0.78  ...                        6.79
 21                0.60  ...                        3.13
 2                 0.96  ...                       68.59
 30                0.37  ...                        7.59
 7                 0.89  ...                        7.19
 5                 0.99  ...                       10.32
 19                0.70  ...                       13.21
 20                0.79  ...                       11.70
 10                0.96  ...                        7.67
 8                 1.09  ...                        2.59
 26                0.47  ...                        9.14
 4                 0.78  ...                       11.73
 1                 1.13  ...                       16.08
 22                0.60  ...                        2.95
 16                0.64  ...                       15.82
 13                0.42  ...                       24.60

           size_zone_nonuniformity  zone_percentage  \
 Patients
 23                           7.59             0.00
 6                            7.92             0.00
 17                           6.03             0.00
 9                           30.46             0.02
 15                           6.14             0.00
 24                          13.57             0.00
 21                           7.07             0.00
 2                           37.58             0.00
 30                          17.08             0.00
 7                           11.14             0.00
 5                            5.95             0.00
 19                           7.08             0.00
 20                          13.50             0.00
 10                           7.62             0.02
 8                            3.77             0.00
 26                          12.18             0.00
 4                            8.39             0.00
 1                           25.22             0.00
 22                          10.45             0.00
 16                          22.87             0.00
 13                          14.46             0.00

           low_gray_level_zone_emphasis  high_gray_level_zone_emphasis  \
 Patients
 23                                0.13                   3.365668e+06
 6                                 0.33                   3.082371e+06
 17                                0.25                   3.242638e+06
 9                                 0.35                   1.049818e+04
 15                                0.31                   8.623205e+07
 24                                0.34                   1.580597e+07
 21                                0.29                   1.517345e+07
 2                                 0.40                   2.941573e+08
 30                                0.30                   2.553528e+08
 7                                 0.25                   7.772283e+07
 5                                 0.36                   1.278671e+07
 19                                0.36                   5.708569e+06
 20                                0.31                   2.481976e+07
 10                                0.28                   3.609890e+03
 8                                 0.21                   1.662223e+06
 26                                0.35                   8.892132e+06
 4                                 0.29                   1.263940e+07
 1                                 0.23                   9.939963e+07
 22                                0.12                   1.439837e+07
 16                                0.25                   2.545060e+08
 13                                0.35                   1.342649e+07

           small_zone_low_gray_level_emphasis  \
 Patients
 23                                      0.02
 6                                       0.01
 17                                      0.03
 9                                       0.03
 15                                      0.03
 24                                      0.05
 21                                      0.04
 2                                       0.01
 30                                      0.03
 7                                       0.02
 5                                       0.01
 19                                      0.02
 20                                      0.02
 10                                      0.01
 8                                       0.01
 26                                      0.05
 4                                       0.01
 1                                       0.01
 22                                      0.01
 16                                      0.02
 13                                      0.01

           small_zone_high_gray_level_emphasis  \
 Patients
 23                               3.115217e+06
 6                                3.017416e+06
 17                               3.211116e+06
 9                                3.211200e+02
 15                               8.618371e+07
 24                               1.548672e+07
 21                               1.496157e+07
 2                                2.939368e+08
 30                               2.522005e+08
 7                                7.742148e+07
 5                                1.277919e+07
 19                               5.682747e+06
 20                               2.425409e+07
 10                               3.368000e+02
 8                                1.625534e+06
 26                               8.492991e+06
 4                                1.259057e+07
 1                                9.860538e+07
 22                               1.404829e+07
 16                               2.544970e+08
 13                               1.332718e+07

           large_zone_low_gray_level_emphasis  \
 Patients
 23                                      1.87
 6                                      23.82
 17                                      7.07
 9                                      15.54
 15                                      8.79
 24                                      6.42
 21                                      3.52
 2                                      28.57
 30                                      5.30
 7                                       9.02
 5                                      31.71
 19                                     35.20
 20                                     10.32
 10                                     22.22
 8                                      12.66
 26                                      7.04
 4                                      31.82
 1                                      11.75
 22                                      1.84
 16                                     10.52
 13                                     33.30

           large_zone_high_gray_level_emphasis  filter_$
 Patients
 23                               6.583081e+06         0
 6                                5.376431e+06         0
 17                               3.975808e+06         0
 9                                4.590263e+05         0
 15                               8.747664e+07         1
 24                               2.260249e+07         0
 21                               1.937328e+07         0
 2                                3.034294e+08         0
 30                               2.806385e+08         0
 7                                8.304376e+07         0
 5                                1.305688e+07         0
 19                               6.127380e+06         0
 20                               3.749502e+07         0
 10                               1.051140e+05         0
 8                                2.738375e+06         0
 26                               1.979140e+07         0
 4                                1.366822e+07         0
 1                                1.229531e+08         0
 22                               2.027571e+07         0
 16                               2.548466e+08         1
 13                               1.521203e+07         1

 [21 rows x 106 columns],
           VisualG  SUVmax   TBR  ConclusionPET  ABusepostoper  \
 Patients
 3               3     5.3  4.42              1              1
 29              3     3.7  2.85              2              2
 14              3     3.5  1.94              3              1
 11              0     4.9  2.89              2              1
 27              2     4.7  3.13              2              2
 25              3     5.9  3.47              2              2
 28              2     3.2  2.91              2              2
 12              4     6.9  3.83              3              1
 18              1     3.0  2.14              2              1

           minimum_intensity  maximum_intensity  range  mean_intensity  \
 Patients
 3                      0.08               5.28   5.20            1.72
 29                     0.39               3.69   3.30            1.75
 14                     0.67               3.46   2.78            2.14
 11                     0.28               4.91   4.63            1.76
 27                     0.32               4.54   4.22            1.80
 25                     0.92               5.08   4.16            2.72
 28                     0.78               3.01   2.23            1.66
 12                     0.38               6.93   6.56            2.49
 18                     0.55               2.94   2.40            1.47

           quantile0025  ...  gray_level_nonuniformity_A  \
 Patients                ...
 3                 0.32  ...                       20.20
 29                0.87  ...                        6.16
 14                1.10  ...                        2.21
 11                0.54  ...                       13.41
 27                0.65  ...                        9.03
 25                1.54  ...                        8.30
 28                1.11  ...                        4.00
 12                0.75  ...                       29.67
 18                0.81  ...                       11.95

           size_zone_nonuniformity  zone_percentage  \
 Patients
 3                           18.46              0.0
 29                           9.96              0.0
 14                           4.29              0.0
 11                          15.37              0.0
 27                          10.52              0.0
 25                          10.65              0.0
 28                           6.71              0.0
 12                          28.04              0.0
 18                          18.20              0.0

           low_gray_level_zone_emphasis  high_gray_level_zone_emphasis  \
 Patients
 3                                 0.36                   1.688961e+09
 29                                0.33                   8.157497e+06
 14                                0.22                   1.603004e+06
 11                                0.32                   9.204362e+08
 27                                0.33                   2.079918e+07
 25                                0.38                   8.774879e+06
 28                                0.36                   6.473374e+06
 12                                0.34                   1.247711e+08
 18                                0.39                   6.186955e+07

           small_zone_low_gray_level_emphasis  \
 Patients
 3                                       0.03
 29                                      0.04
 14                                      0.02
 11                                      0.03
 27                                      0.04
 25                                      0.02
 28                                      0.03
 12                                      0.02
 18                                      0.03

           small_zone_high_gray_level_emphasis  \
 Patients
 3                                1.688835e+09
 29                               7.859610e+06
 14                               1.595393e+06
 11                               9.202316e+08
 27                               2.063673e+07
 25                               8.732541e+06
 28                               6.462423e+06
 12                               1.247132e+08
 18                               6.062504e+07

           large_zone_low_gray_level_emphasis  \
 Patients
 3                                      10.02
 29                                      5.64
 14                                      4.07
 11                                      7.57
 27                                      7.89
 25                                     12.79
 28                                      6.26
 12                                     12.28
 18                                      9.68

           large_zone_high_gray_level_emphasis  filter_$
 Patients
 3                                1.691300e+09         0
 29                               1.403711e+07         0
 14                               1.812258e+06         1
 11                               9.241926e+08         1
 27                               2.414572e+07         0
 25                               1.052670e+07         0
 28                               6.675458e+06         0
 12                               1.270904e+08         1
 18                               8.133587e+07         0

 [9 rows x 106 columns])

In [6]:
#Scaling the data
scaler = StandardScaler()
scaler.fit(X_train.fillna(0))

StandardScaler()

In [7]:
#Selecting features using Lasso regularisation using SelectFromModel
sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l1', solver='liblinear'))
sel_.fit(scaler.transform(X_train.fillna(0)), y_train)

SelectFromModel(estimator=LogisticRegression(C=1, penalty='l1',
                                             solver='liblinear'))

In [8]:
#Visualising features that were kept by the lasso regularisation
sel_.get_support()

array([False, False, False,  True,  True,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True])

In [9]:
#In the above output, the output labels are index wise. So True is for the features that lasso thought is important (non-zero features) while False is for the features whose weights were shrinked to zero and are not important according to Lasso.

In [10]:
selected_feat = X_train.columns[(sel_.get_support())]
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 106
selected features: 7
features with coefficients shrank to zero: 99

In [11]:
#visualizing the selected features
selected_feat

Index(['ConclusionPET', 'ABusepostoper', 'minimum_intensity', 'quantile0025',
       'information_measure_of_correlation1_max', 'long_run_emphasis_mean',
       'filter_$'],
      dtype='object')

In [12]:
np.sum(sel_.estimator_.coef_ == 0)

99

In [13]:
#Identifying the removed features
removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index(['VisualG', 'SUVmax', 'TBR', 'maximum_intensity', 'range',
       'mean_intensity', 'quantile25', 'median_intensity', 'quantile75',
       'quantile975', 'sum', 'variance', 'standard_deviation', 'skewness',
       'kurtosis', 'energy', 'entropy', 'mean_absolute_deviation',
       'root_mean_square', 'uniformity', 'autocorrection_mean',
       'autocorrection_max', 'contrast_mean', 'contrast_max',
       'correlation_mean', 'correlation_max', 'haralicks_correlation_mean',
       'haralicks_correlation_max', 'cluster_prominence_mean',
       'cluster_prominence_max', 'cluster_shade_mean', 'cluster_shade_max',
       'cluster_tendency_mean', 'cluster_tendency_max', 'dissimilarity_mean',
       'dissimilarity_max', 'energy_mean', 'energy_A', 'entropy_mean',
       'entropy_max', 'homogeneity1_mean', 'homogeneity1_max',
       'homogeneity2_mean', 'homogeneity2_max', 'maximum_probability_mean',
       'maximum_probability_max', 'sum_of_squares_mean', 'sum_of_squares_max',
       'sum_average_mean', 'sum_average_max', 'sum_entropy', 'sum_entropy_max',
       'sum_variance_mean', 'sum_variance_max', 'difference_variance1_mean',
       'difference_variance1_max', 'difference_variance2_mean',
       'difference_variance2_max', 'difference_entropy_mean',
       'difference_entropy_max', 'information_measure_of_correlation1_mean',
       'information_measure_of_correlation2_mean',
       'information_measure_of_correlation2_max',
       'inverse_difference_moment_normalized_mean',
       'inverse_difference_moment_normalized_max',
       'inverse_difference_normalized_mean',
       'inverse_difference_normalized_max', 'short_run_emphasis_mean',
       'short_run_emphasis_max', 'long_run_emphasis_max',
       'gray_level_nonuniformity_mean', 'gray_level_nonuniformity_max',
       'run_length_nonuniformity_mean', 'run_length_nonuniformity_max',
       'run_percentage_mean', 'run_percentage_max',
       'low_gray_level_run_emphasis_mean', 'low_gray_level_run_emphasis_max',
       'high_gray_level_run_emphasis_mean', 'high_gray_level_run_emphasis_max',
       'short_run_low_gray_level_emphasis_mean',
       'short_run_low_gray_level_emphasis_max',
       'short_run_high_gray_level_emphasis_mean',
       'short_run_high_gray_level_emphasis_max',
       'long_run_low_gray_level_emphasis_mean',
       'long_run_low_gray_level_emphasis_max',
       'long_run_high_gray_level_emphasis_mean',
       'long_run_high_gray_level_emphasis_max', 'small_zone_emphasis',
       'large_zone_emphasis', 'gray_level_nonuniformity_A',
       'size_zone_nonuniformity', 'zone_percentage',
       'low_gray_level_zone_emphasis', 'high_gray_level_zone_emphasis',
       'small_zone_low_gray_level_emphasis',
       'small_zone_high_gray_level_emphasis',
       'large_zone_low_gray_level_emphasis',
       'large_zone_high_gray_level_emphasis'],
      dtype='object')

In [14]:
#Removing the features from the training and testing set
X_train_selected = sel_.transform(X_train.fillna(0))
X_test_selected = sel_.transform(X_test.fillna(0))
X_train_selected.shape, X_test_selected.shape

((21, 7), (9, 7))