In [1]:
#Importing important libraries
import pandas as pd
from sklearn.preprocessing import normalize

In [2]:
#Loading the dataset
patients_data = pd.read_csv("plan b data.csv", index_col=0)

In [3]:
#In practice, feature selection should be done after data pre-processing, so ideally, all the categorical variables are encoded into numbers
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(patients_data.select_dtypes(include=numerics).columns)
patients_data = patients_data[numerical_vars]
patients_data

,Diagnosis,VisualG,SUVmax,TBR,ConclusionPET,ABusepostoper,minimum_intensity,maximum_intensity,range,mean_intensity,...,gray_level_nonuniformity_A,size_zone_nonuniformity,zone_percentage,low_gray_level_zone_emphasis,high_gray_level_zone_emphasis,small_zone_low_gray_level_emphasis,small_zone_high_gray_level_emphasis,large_zone_low_gray_level_emphasis,large_zone_high_gray_level_emphasis,filter_$
Patients,,,,,,,,,,,,,,,,,,,,,
1,1,4,6.7,3.72,2,1,0.62,6.68,6.07,2.34,...,16.08,25.22,0.00,0.23,9.939963e+07,0.01,9.860538e+07,11.75,1.229531e+08,0
2,1,3,9.8,4.90,1,1,0.34,9.66,9.32,2.61,...,68.59,37.58,0.00,0.40,2.941573e+08,0.01,2.939368e+08,28.57,3.034294e+08,0
3,1,3,5.3,4.42,1,1,0.08,5.28,5.20,1.72,...,20.20,18.46,0.00,0.36,1.688961e+09,0.03,1.688835e+09,10.02,1.691300e+09,0
4,1,4,11.2,10.18,1,1,0.47,8.50,8.03,2.21,...,11.73,8.39,0.00,0.29,1.263940e+07,0.01,1.259057e+07,31.82,1.366822e+07,0
5,1,4,9.1,6.59,1,1,0.60,8.30,7.70,2.71,...,10.32,5.95,0.00,0.36,1.278671e+07,0.01,1.277919e+07,31.71,1.305688e+07,0
6,1,4,6.3,3.94,1,1,0.70,6.28,5.58,2.70,...,6.46,7.92,0.00,0.33,3.082371e+06,0.01,3.017416e+06,23.82,5.376431e+06,0
7,1,4,4.9,4.45,1,1,0.48,4.87,4.39,1.70,...,7.19,11.14,0.00,0.25,7.772283e+07,0.02,7.742148e+07,9.02,8.304376e+07,0
8,1,4,6.1,4.69,1,1,0.82,6.11,5.29,2.36,...,2.59,3.77,0.00,0.21,1.662223e+06,0.01,1.625534e+06,12.66,2.738375e+06,0
9,1,3,10.3,2.86,1,1,0.44,6.76,6.32,3.01,...,43.75,30.46,0.02,0.35,1.049818e+04,0.03,3.211200e+02,15.54,4.590263e+05,0
10,1,2,7.5,2.88,3,1,0.68,7.49,6.81,3.02,...,7.67,7.62,0.02,0.28,3.609890e+03,0.01,3.368000e+02,22.22,1.051140e+05,0
11,0,0,4.9,2.89,2,1,0.28,4.91,4.63,1.76,...,13.41,15.37,0.00,0.32,9.204362e+08,0.03,9.202316e+08,7.57,9.241926e+08,1
12,0,4,6.9,3.83,3,1,0.38,6.93,6.56,2.49,...,29.67,28.04,0.00,0.34,1.247711e+08,0.02,1.247132e+08,12.28,1.270904e+08,1
13,0,4,9.3,7.75,3,1,0.20,9.29,9.09,1.82,...,24.60,14.46,0.00,0.35,1.342649e+07,0.01,1.332718e+07,33.30,1.521203e+07,1
14,0,3,3.5,1.94,3,1,0.67,3.46,2.78,2.14,...,2.21,4.29,0.00,0.22,1.603004e+06,0.02,1.595393e+06,4.07,1.812258e+06,1
15,0,3,4.3,2.15,2,1,0.39,4.28,3.89,1.90,...,5.00,6.14,0.00,0.31,8.623205e+07,0.03,8.618371e+07,8.79,8.747664e+07,1
16,0,3,6.1,4.36,3,1,0.21,6.08,5.87,2.49,...,15.82,22.87,0.00,0.25,2.545060e+08,0.02,2.544970e+08,10.52,2.548466e+08,1
17,0,2,4.8,2.18,3,2,0.37,4.80,4.43,1.79,...,3.22,6.03,0.00,0.25,3.242638e+06,0.03,3.211116e+06,7.07,3.975808e+06,0
18,0,1,3.0,2.14,2,1,0.55,2.94,2.40,1.47,...,11.95,18.20,0.00,0.39,6.186955e+07,0.03,6.062504e+07,9.68,8.133587e+07,0
19,0,0,9.3,7.75,2,2,0.44,9.29,8.85,1.73,...,13.21,7.08,0.00,0.36,5.708569e+06,0.02,5.682747e+06,35.20,6.127380e+06,0
20,0,2,4.3,3.07,2,2,0.32,4.32,4.00,1.92,...,11.70,13.50,0.00,0.31,2.481976e+07,0.02,2.425409e+07,10.32,3.749502e+07,0
21,0,1,3.0,1.67,2,2,0.37,3.02,2.64,1.60,...,3.13,7.07,0.00,0.29,1.517345e+07,0.04,1.496157e+07,3.52,1.937328e+07,0
22,0,1,2.6,1.63,2,2,0.34,2.60,2.26,1.48,...,2.95,10.45,0.00,0.12,1.439837e+07,0.01,1.404829e+07,1.84,2.027571e+07,0
23,0,1,2.4,3.43,2,2,0.15,2.67,2.52,1.22,...,1.81,7.59,0.00,0.13,3.365668e+06,0.02,3.115217e+06,1.87,6.583081e+06,0
24,0,1,3.4,1.70,2,2,0.36,3.44,3.09,1.84,...,6.79,13.57,0.00,0.34,1.580597e+07,0.05,1.548672e+07,6.42,2.260249e+07,0
25,0,3,5.9,3.47,2,2,0.92,5.08,4.16,2.72,...,8.30,10.65,0.00,0.38,8.774879e+06,0.02,8.732541e+06,12.79,1.052670e+07,0
26,0,0,5.6,3.29,3,2,0.25,5.60,5.35,2.12,...,9.14,12.18,0.00,0.35,8.892132e+06,0.05,8.492991e+06,7.04,1.979140e+07,0
27,0,2,4.7,3.13,2,2,0.32,4.54,4.22,1.80,...,9.03,10.52,0.00,0.33,2.079918e+07,0.04,2.063673e+07,7.89,2.414572e+07,0
28,0,2,3.2,2.91,2,2,0.78,3.01,2.23,1.66,...,4.00,6.71,0.00,0.36,6.473374e+06,0.03,6.462423e+06,6.26,6.675458e+06,0
29,0,3,3.7,2.85,2,2,0.39,3.69,3.30,1.75,...,6.16,9.96,0.00,0.33,8.157497e+06,0.04,7.859610e+06,5.64,1.403711e+07,0
30,0,1,2.5,1.92,2,2,0.22,2.52,2.30,0.94,...,7.59,17.08,0.00,0.30,2.553528e+08,0.03,2.522005e+08,5.30,2.806385e+08,0

In [4]:
#data type of variables
patients_data.dtypes

Diagnosis                                int64
VisualG                                  int64
SUVmax                                 float64
TBR                                    float64
ConclusionPET                            int64
                                        ...
small_zone_low_gray_level_emphasis     float64
small_zone_high_gray_level_emphasis    float64
large_zone_low_gray_level_emphasis     float64
large_zone_high_gray_level_emphasis    float64
filter_$                                 int64
Length: 107, dtype: object

In [5]:
patients_data.isnull().sum()

Diagnosis                              0
VisualG                                0
SUVmax                                 0
TBR                                    0
ConclusionPET                          0
                                      ..
small_zone_low_gray_level_emphasis     0
small_zone_high_gray_level_emphasis    0
large_zone_low_gray_level_emphasis     0
large_zone_high_gray_level_emphasis    0
filter_$                               0
Length: 107, dtype: int64

In [6]:
#Creating the traning set of the features
data = patients_data.drop(['Diagnosis'], axis=1)

In [7]:
normalize = normalize(data)

In [8]:
data_scaled = pd.DataFrame(normalize)
data_scaled.var()

0      1.284372e-13
1      1.198437e-12
2      2.051581e-13
3      2.114340e-13
4      2.541095e-14
           ...
101    3.742182e-18
102    3.007153e-02
103    1.034799e-11
104    2.410101e-02
105    3.837190e-15
Length: 106, dtype: float64

In [9]:
#storing the variance and name of variables
variance = data_scaled.var()
columns = data.columns

In [10]:
#saving the names of variables having variance more than a threshold value

variable = [ ]

for i in range(0,len(variance)):
    if variance[i]>=0.006: #setting the threshold as 1%
        variable.append(columns[i])

In [11]:
variable

['uniformity',
 'high_gray_level_zone_emphasis',
 'small_zone_high_gray_level_emphasis',
 'large_zone_high_gray_level_emphasis']

In [12]:
# creating a new dataframe using the above variables
new_data = data[variable]

# first five rows of the new data
new_data.head()

,uniformity,high_gray_level_zone_emphasis,small_zone_high_gray_level_emphasis,large_zone_high_gray_level_emphasis
Patients,,,,
1,359620690.0,9.939963e+07,9.860538e+07,1.229531e+08
2,259620895.0,2.941573e+08,2.939368e+08,3.034294e+08
3,62710650.0,1.688961e+09,1.688835e+09,1.691300e+09
4,14400761.0,1.263940e+07,1.259057e+07,1.366822e+07
5,1937109.0,1.278671e+07,1.277919e+07,1.305688e+07